// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'ObjectBox/NamesModelTelugu.dart';
import 'ObjectBox/NamesModelTeluguLiked.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 2575178336258568589),
      name: 'NameData',
      lastPropertyId: const obx_int.IdUid(15, 7931885504604488770),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 554988589444997977),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3803640063055317148),
            name: 'docId',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(1, 7250842580150328908)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3082159135345188576),
            name: 'englishName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7556224482895168289),
            name: 'teluguName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8052170515144191112),
            name: 'firstLetterEnglish',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 7812827598183989062),
            name: 'firstLetterTelugu',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(2, 86593971580271955)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5366609929440107392),
            name: 'gender',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 4911248977351714063),
            name: 'language',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 8084114296822984049),
            name: 'religion',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 447245438003669609),
            name: 'meaningEnglish',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 5448342382136285784),
            name: 'meaningTelugu',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 3868283936606490388),
            name: 'origin',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 6399450146117847132),
            name: 'tags',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 7931885504604488770),
            name: 'isLiked',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 4750240983097111712),
      name: 'NameDataLiked',
      lastPropertyId: const obx_int.IdUid(14, 3112366060189258276),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4604792833864215840),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5618200186274583879),
            name: 'docId',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(3, 6563269495283179265)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 165587189170516904),
            name: 'englishName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3632841775541426683),
            name: 'teluguName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3064330510401718725),
            name: 'firstLetterEnglish',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5280063413108870374),
            name: 'firstLetterTelugu',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(4, 5210151339402012397)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2699038002734894455),
            name: 'gender',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 2697829430674085198),
            name: 'language',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 3930354658562960408),
            name: 'religion',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 3616996243301219247),
            name: 'meaningEnglish',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 4329060216703749451),
            name: 'meaningTelugu',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 1097928878195210119),
            name: 'origin',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 3545148422091363480),
            name: 'tags',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 3112366060189258276),
            name: 'isLiked',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 4750240983097111712),
      lastIndexId: const obx_int.IdUid(4, 5210151339402012397),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [8875568885890111180],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    NameData: obx_int.EntityDefinition<NameData>(
        model: _entities[0],
        toOneRelations: (NameData object) => [],
        toManyRelations: (NameData object) => {},
        getId: (NameData object) => object.id,
        setId: (NameData object, int id) {
          object.id = id;
        },
        objectToFB: (NameData object, fb.Builder fbb) {
          final docIdOffset = fbb.writeString(object.docId);
          final englishNameOffset = fbb.writeString(object.englishName);
          final teluguNameOffset = fbb.writeString(object.teluguName);
          final firstLetterEnglishOffset =
              fbb.writeString(object.firstLetterEnglish);
          final firstLetterTeluguOffset =
              fbb.writeString(object.firstLetterTelugu);
          final genderOffset = fbb.writeString(object.gender);
          final languageOffset = fbb.writeString(object.language);
          final religionOffset = fbb.writeString(object.religion);
          final meaningEnglishOffset = fbb.writeString(object.meaningEnglish);
          final meaningTeluguOffset = fbb.writeString(object.meaningTelugu);
          final originOffset = fbb.writeString(object.origin);
          final tagsOffset = fbb.writeList(
              object.tags.map(fbb.writeString).toList(growable: false));
          fbb.startTable(16);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, docIdOffset);
          fbb.addOffset(2, englishNameOffset);
          fbb.addOffset(3, teluguNameOffset);
          fbb.addOffset(4, firstLetterEnglishOffset);
          fbb.addOffset(5, firstLetterTeluguOffset);
          fbb.addOffset(6, genderOffset);
          fbb.addOffset(7, languageOffset);
          fbb.addOffset(8, religionOffset);
          fbb.addOffset(9, meaningEnglishOffset);
          fbb.addOffset(10, meaningTeluguOffset);
          fbb.addOffset(11, originOffset);
          fbb.addOffset(13, tagsOffset);
          fbb.addBool(14, object.isLiked);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final docIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final englishNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final teluguNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final firstLetterEnglishParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final firstLetterTeluguParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final genderParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final languageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final religionParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 20, '');
          final meaningEnglishParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 22, '');
          final meaningTeluguParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 24, '');
          final originParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 26, '');
          final tagsParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGet(buffer, rootOffset, 30, []);
          final isLikedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 32, false);
          final object = NameData(
              id: idParam,
              docId: docIdParam,
              englishName: englishNameParam,
              teluguName: teluguNameParam,
              firstLetterEnglish: firstLetterEnglishParam,
              firstLetterTelugu: firstLetterTeluguParam,
              gender: genderParam,
              language: languageParam,
              religion: religionParam,
              meaningEnglish: meaningEnglishParam,
              meaningTelugu: meaningTeluguParam,
              origin: originParam,
              tags: tagsParam,
              isLiked: isLikedParam);

          return object;
        }),
    NameDataLiked: obx_int.EntityDefinition<NameDataLiked>(
        model: _entities[1],
        toOneRelations: (NameDataLiked object) => [],
        toManyRelations: (NameDataLiked object) => {},
        getId: (NameDataLiked object) => object.id,
        setId: (NameDataLiked object, int id) {
          object.id = id;
        },
        objectToFB: (NameDataLiked object, fb.Builder fbb) {
          final docIdOffset = fbb.writeString(object.docId);
          final englishNameOffset = fbb.writeString(object.englishName);
          final teluguNameOffset = fbb.writeString(object.teluguName);
          final firstLetterEnglishOffset =
              fbb.writeString(object.firstLetterEnglish);
          final firstLetterTeluguOffset =
              fbb.writeString(object.firstLetterTelugu);
          final genderOffset = fbb.writeString(object.gender);
          final languageOffset = fbb.writeString(object.language);
          final religionOffset = fbb.writeString(object.religion);
          final meaningEnglishOffset = fbb.writeString(object.meaningEnglish);
          final meaningTeluguOffset = fbb.writeString(object.meaningTelugu);
          final originOffset = fbb.writeString(object.origin);
          final tagsOffset = fbb.writeList(
              object.tags.map(fbb.writeString).toList(growable: false));
          fbb.startTable(15);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, docIdOffset);
          fbb.addOffset(2, englishNameOffset);
          fbb.addOffset(3, teluguNameOffset);
          fbb.addOffset(4, firstLetterEnglishOffset);
          fbb.addOffset(5, firstLetterTeluguOffset);
          fbb.addOffset(6, genderOffset);
          fbb.addOffset(7, languageOffset);
          fbb.addOffset(8, religionOffset);
          fbb.addOffset(9, meaningEnglishOffset);
          fbb.addOffset(10, meaningTeluguOffset);
          fbb.addOffset(11, originOffset);
          fbb.addOffset(12, tagsOffset);
          fbb.addBool(13, object.isLiked);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final docIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final englishNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final teluguNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final firstLetterEnglishParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final firstLetterTeluguParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final genderParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final languageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final religionParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 20, '');
          final meaningEnglishParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 22, '');
          final meaningTeluguParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 24, '');
          final originParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 26, '');
          final tagsParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGet(buffer, rootOffset, 28, []);
          final isLikedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 30, false);
          final object = NameDataLiked(
              id: idParam,
              docId: docIdParam,
              englishName: englishNameParam,
              teluguName: teluguNameParam,
              firstLetterEnglish: firstLetterEnglishParam,
              firstLetterTelugu: firstLetterTeluguParam,
              gender: genderParam,
              language: languageParam,
              religion: religionParam,
              meaningEnglish: meaningEnglishParam,
              meaningTelugu: meaningTeluguParam,
              origin: originParam,
              tags: tagsParam,
              isLiked: isLikedParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [NameData] entity fields to define ObjectBox queries.
class NameData_ {
  /// See [NameData.id].
  static final id =
      obx.QueryIntegerProperty<NameData>(_entities[0].properties[0]);

  /// See [NameData.docId].
  static final docId =
      obx.QueryStringProperty<NameData>(_entities[0].properties[1]);

  /// See [NameData.englishName].
  static final englishName =
      obx.QueryStringProperty<NameData>(_entities[0].properties[2]);

  /// See [NameData.teluguName].
  static final teluguName =
      obx.QueryStringProperty<NameData>(_entities[0].properties[3]);

  /// See [NameData.firstLetterEnglish].
  static final firstLetterEnglish =
      obx.QueryStringProperty<NameData>(_entities[0].properties[4]);

  /// See [NameData.firstLetterTelugu].
  static final firstLetterTelugu =
      obx.QueryStringProperty<NameData>(_entities[0].properties[5]);

  /// See [NameData.gender].
  static final gender =
      obx.QueryStringProperty<NameData>(_entities[0].properties[6]);

  /// See [NameData.language].
  static final language =
      obx.QueryStringProperty<NameData>(_entities[0].properties[7]);

  /// See [NameData.religion].
  static final religion =
      obx.QueryStringProperty<NameData>(_entities[0].properties[8]);

  /// See [NameData.meaningEnglish].
  static final meaningEnglish =
      obx.QueryStringProperty<NameData>(_entities[0].properties[9]);

  /// See [NameData.meaningTelugu].
  static final meaningTelugu =
      obx.QueryStringProperty<NameData>(_entities[0].properties[10]);

  /// See [NameData.origin].
  static final origin =
      obx.QueryStringProperty<NameData>(_entities[0].properties[11]);

  /// See [NameData.tags].
  static final tags =
      obx.QueryStringVectorProperty<NameData>(_entities[0].properties[12]);

  /// See [NameData.isLiked].
  static final isLiked =
      obx.QueryBooleanProperty<NameData>(_entities[0].properties[13]);
}

/// [NameDataLiked] entity fields to define ObjectBox queries.
class NameDataLiked_ {
  /// See [NameDataLiked.id].
  static final id =
      obx.QueryIntegerProperty<NameDataLiked>(_entities[1].properties[0]);

  /// See [NameDataLiked.docId].
  static final docId =
      obx.QueryStringProperty<NameDataLiked>(_entities[1].properties[1]);

  /// See [NameDataLiked.englishName].
  static final englishName =
      obx.QueryStringProperty<NameDataLiked>(_entities[1].properties[2]);

  /// See [NameDataLiked.teluguName].
  static final teluguName =
      obx.QueryStringProperty<NameDataLiked>(_entities[1].properties[3]);

  /// See [NameDataLiked.firstLetterEnglish].
  static final firstLetterEnglish =
      obx.QueryStringProperty<NameDataLiked>(_entities[1].properties[4]);

  /// See [NameDataLiked.firstLetterTelugu].
  static final firstLetterTelugu =
      obx.QueryStringProperty<NameDataLiked>(_entities[1].properties[5]);

  /// See [NameDataLiked.gender].
  static final gender =
      obx.QueryStringProperty<NameDataLiked>(_entities[1].properties[6]);

  /// See [NameDataLiked.language].
  static final language =
      obx.QueryStringProperty<NameDataLiked>(_entities[1].properties[7]);

  /// See [NameDataLiked.religion].
  static final religion =
      obx.QueryStringProperty<NameDataLiked>(_entities[1].properties[8]);

  /// See [NameDataLiked.meaningEnglish].
  static final meaningEnglish =
      obx.QueryStringProperty<NameDataLiked>(_entities[1].properties[9]);

  /// See [NameDataLiked.meaningTelugu].
  static final meaningTelugu =
      obx.QueryStringProperty<NameDataLiked>(_entities[1].properties[10]);

  /// See [NameDataLiked.origin].
  static final origin =
      obx.QueryStringProperty<NameDataLiked>(_entities[1].properties[11]);

  /// See [NameDataLiked.tags].
  static final tags =
      obx.QueryStringVectorProperty<NameDataLiked>(_entities[1].properties[12]);

  /// See [NameDataLiked.isLiked].
  static final isLiked =
      obx.QueryBooleanProperty<NameDataLiked>(_entities[1].properties[13]);
}
